Library Project
hemant-soni-vst-au4/library pull request #1
Opened 2020-10-09 17:35 UTC by hemant-soni-vst-au4

### Library Project
- New Book button to add a new book in the library
- Toggle the button to read or unread for reading status
- delete button to delete a book
- static data of library in data,js file

2020-10-09 18:40 UTC, christianotieno requested changes
# Changes Required ♻️ 
Hello team 👋 
Good job on this project. 👍 
Kindly, let's work on the following issues before we proceed 👇  

### Happy coding 💻 

#### Christian Otieno (TSE)

2020-10-09 18:40 UTC, christianotieno commented on README.md
> +
## Improve Readme

- [ ] Let's add a screenshot and instructions on how to well clone and run the project locally (setup). Let's keep it more descriptive enough ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

2020-10-09 18:40 UTC, christianotieno commented on js/index.js
> +};
## Add `read` option to the form submission.
- [ ] During book creation, kindly add the option to add a book. The form should allow the marking the `Book` status as `read`

2020-10-09 18:40 UTC, christianotieno commented on js/index.js
> +    title.value = '';
# Refactor this entire codebase to suit the following 👇 
- [ ] Let's keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright).

2020-10-12 16:40 UTC, hemant-soni-vst-au4 commented
Required changes made. Please clone the repository and run the program. Live link online showing the HTML page only.

2020-10-12 17:02 UTC, whiz25 requested changes
## Changes Required :pray: 
Good job making suggested changes. We however, need to fix a few things before we can merge this PR.
- [x] validate your form inputs. A user should not be able to create a book with empty fields. Fix that.
- [x] Store books in the localStorage in the user's browser. When a user creates a book, they should be able to view that book after reloading their browser. That should not happen. Please fix that.


### Martin Afani

2020-10-12 20:03 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @hemant-soni-vst-au4 @Bekhzod96 :wave: 

### Thank you for making all of the requested changes from the previous TSE, but I believe those changes generated a bug:

- [ ] I can't add any books to the library, I checked both in your live version and also cloned your project.

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-13 06:01 UTC, hemant-soni-vst-au4 commented
there was one silly mistake. Now you can add a new book in the cloned repository.

2020-10-13 06:28 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, CONGRATULATIONS ON FIXING ALL THE COMMENTS OUTLINE BY THE PREVIOUS TSE'S :+1: I hereby approved your project :smile: 

Go ahead and merge into development :fireworks: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-10-13 06:32 UTC, merged